### ISSUE TITLE
Album artist -> artist

### ISSUE THREAD

**Issue by tengl** [esenliyim/sp-tray#13]
Hi, great plugin.
One thing though, shouldn't it be `artist`, not `albumArtist`? https://github.com/esenliyim/sp-tray/blob/master/panelButton.js#L178
I get "Various artists" as artist on some tracks. Can `artist` be empty? If so, `albumArtist` can be a fallback value.

**Comment by esenliyim** [comment]
IIRC those fields were kinda inconsistent in what kind of information they contained, so I made the decision to use `albumArtist` instead of `artist` because the results from that were overall more 'usable'. TBH I don't remember why I really chose that, might look into it again. Or at least offer an option to choose.

**Comment by tengl** [comment]
Yeah, it would be great to have both `artist` and `albumArtist` so that we can chose what to display. 

Maybe you can keep `artist` as it is now (to not break current behavior) and add `trackArtist` to the template keywords so we can choose. Then keep and resolve `artist` more intelligently (future feature), e.g. user track artist if album artist is/contains "Various artists" or something like that.

**Comment by mhatvan** [comment]
I just wanted to report the same thing. When quickly checking which artist the song is from, the `various artists` is confusing me. Especially in trance music, a lot of songs are from some kind of compilation or a collab between multiple artists. 

The suggestions by @tengl sound great!

**Comment by esenliyim** [comment]
Okay, I've investigated it and it seems you're both right. 

When the album belongs to artist A but a song in it features another artist B (or all the way up to Z), you only get A in both fields anyway. The other artists don't seem to get any mention anywhere in the dbus metadata string. In the case of a collab/compilation album, which I had to really look for because apparently I don't have any in my playlists, `albumArists` seems to become completely useless.

So what I've found is I can actually ditch `albumArtist` and switch straight to `artist` altogether without offering the option to choose because `albumArtist` doesn't seem to offer anything extra so there's no reason to actually use it. Don't know what I was thinking when I picked that field back then. 

However I'd still appreciate it if you could give me some "problem tracks" you've encountered so I can check out their metadata before I make my final decision.

**Comment by mhatvan** [comment]
Here are some problem tracks, it's mainly compilations but also albums:
https://open.spotify.com/album/3EUcfWnaUaWYGReRJ3rsrA?si=3ymfNSf4RqmD4rnY2PVoAA
https://open.spotify.com/album/0LPWRC0IvHl56c0dxjOoFw?si=HXSSW2BdTj6wdX_kRYwVBQ
https://open.spotify.com/album/04rz93AqGy9JduzV3K81Dh?si=zAkTK5PdS1iS6noJxtVHyg
https://open.spotify.com/album/2oHJAIuw8IH9SUSk05JjRy?si=sbYmzxZtSZid5X492BBrjw

**Comment by esenliyim** [comment]
Thank you, will work on it when I get the chance.

**Comment by esenliyim** [comment]
I have ditched `albumArtist`, it's just `artist` now. 

You can clone from github and start using it right now, but I'll probably update the version on the extensions website once I've figured out #12
