### ISSUE TITLE
Max 4 characters in inactive and paused

### ISSUE THREAD

**Issue by isXander** [esenliyim/sp-tray#31]
I am trying to modify the the inactive and paused text but the text box is limited at four characters, making it impossible to use {metadata}

**Comment by esenliyim** [comment]
That's expected behavior. That character limit was extended when the ´{metadata}´ placeholder was implemented, before that you wouldn't be able to use it even without a character limit. It'd just show the text "{metadata}" without replacing it with the metadata information.

Unfortunately I haven't uploaded that version to the extension website yet. You can clone the repo and manually install it though.

**Comment by isXander** [comment]
Still has a character limit of 4 for the inactive. I can't change it to something like `Nothing is playing`

**Comment by esenliyim** [comment]
Oh, inactive. I missed that part. Yeah I guess I could increase that one too. TBH I don't even remember why I limited them in the first place.

**Comment by esenliyim** [comment]
I've extended the character limits to 25 with the latest push. Still not on the website, but I'll upload it soon after a little more testing to make sure it's fine.
