### ISSUE TITLE
Feature Request: Add Marquee when Text Overflow

### ISSUE THREAD

**Issue by yusuftaufiq** [esenliyim/sp-tray#35]
First, I want to appreciate this Gnome extension that has been created. If possible, I'd like to request a feature to scroll horizontally automatically when the artist name, song title, or album is truncated.
![Screenshot from 2022-10-27 22-13-59](https://user-images.githubusercontent.com/52187958/198330802-b77c8484-5abb-45af-9874-a362d4cdf533.png)

What I'm imagining is something like a marquee feature on an HTML tag like on the [following page](https://www.w3docs.com/learn-html/html-marquee-tag.html).

Thanks!

**Comment by esenliyim** [comment]
I considered that a long time ago, but back then Gtk offered no built-in way of doing it and I thought messing with timeouts to manually animate text was too much work for a simple project like this.

Maybe Gtk4 has better ways of doing it now though, I'll check it out.

**Comment by esenliyim** [comment]
I've looked into it and apparently there's still no built-in way to do it in Gtk, and I still gotta manually animate the scrolling text.

So that's what I'll be doing because I kinda want this feature now. I shall have it ready Soon™.

**Comment by esenliyim** [comment]
The feature is now in the dev branch, you could check it out if you like. It's got configurable length and speed (in the form of frame duration, between 100ms and 20s), and you can change the "separator" thing that goes between the head and the tail of the label as it loops around. Not sure what to call it.

I'd also appreciate any feedback.

**Comment by yusuftaufiq** [comment]
I have tested it. It works well and exceeds what I expected. Thanks!

**Comment by esenliyim** [comment]
So the last version that I pushed works _kinda_ like what you first asked. That is it starts to "scroll horizontally automatically when the artist name, song title, or album is truncated" IF you have the marquee mode enabled and the text length exceeds the max marquee length that's been set (default 50). Otherwise it's just a static text. 

E.g. "Blur | Song 2" will remain a static text cause it's short, but "Rush | 2112: Overture / The Temples Of Syrinx / Discovery / Presentation / Oracle / Soliloquy / Grand Finale - Medley" will automatically start scrolling.

And with that I'm closing this issue.
