### ISSUE TITLE
Support GNOME 45

### ISSUE THREAD

**Issue by mcmxcdev** [esenliyim/sp-tray#42]
See more under https://release.gnome.org/45/developers/index.html and https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by jothi-prasath** [comment]
+1

**Comment by esenliyim** [comment]
Well I guess I know what I'm doing this weekend.

**Comment by esenliyim** [comment]
I've officially started work by building over in @mcmxcdev's #43 on a new branch. I've managed to at least get gnome shell to load the extension, but I feel it's gonna take a bit of work to get it working completely. Biggest problems so far:

1. The settings window straight up doesn't work. I got it displaying some random aksdjhask text right now, but that's it.

2. DBus is doing weird stuff, gonna have to look into that.

All along the way I'll have to fix weird bugs by chasing one-line error messages because I haven't quite figured out how extension errors are getting logged in gnome 45. Also the "upgrading to 45" guide is fine, but it's incomplete and it seems to have some significant holes in it, which left me scratching my head at least a couple times already.

Anyway, that's the current state of things, for all 4 people (if that) in the world who may or may not care.

**Comment by mcmxcdev** [comment]
I also struggled with the upgrading to v45 guide, leaving a lot of open questions. I can offer to help some more if you let me know what your usual workflow is for running and testing out the extension is.

As a side note: Ubuntu 23.10 is supposedly to be released today with GNOME 45, so that might leave some users who decide to upgrade with a non-working extension. This extension is awesome, I am sure it could become popular with some effort!

**Comment by esenliyim** [comment]
Appreciate the offer but I am almost done with it. Already pushed a few commits to the refactor branch, working on the finishing touches now. I should be able to upload the thing to e.g.o shortly.

Turns out I grossly overestimated the required effort hehe.

**Comment by esenliyim** [comment]
After an unusually long wait for approval, the new version is now up on e.g.o.
