### ISSUE TITLE
Multiple Player support (vlc, rhythmbox and such)

### ISSUE THREAD

**Issue by Moon-0xff** [esenliyim/sp-tray#5]
I recently stumbled upon this extension while developing my own.
I wanted to make a pull request for this but i can't seem to be able to hook up my code to yours reliably.

[Take a look at it.](https://github.com/Moon-0xff/mpris-music-label/blob/main/extension.js)
the `getPlayer` function returns a list of mpris compatible players (if you delete the `[0]` in the return statement).
If you hook it up to your code somehow and do some extra stuff you might make your extension work in any mpris compatible player.

I didn't notice it until today but i'm basically making the same extension as you. i was fairly sure your extension was some derivation of [mediaplayer](https://github.com/hellomouse/gnome-shell-extensions-mediaplayer).

I also noticed you changed your label format to the same i use. Did you see my [pull request](https://github.com/mheine/gnome-shell-spotify-label/pull/32)?

Anyway I hope you find this helpful.

**Comment by esenliyim** [comment]
Honestly I made this one for my personal use, which I then figured I could upload to gnome.extensions because why not. What I wanted/needed was just something to show what's playing on spotify, nothing more. I made it specifically unlike mediaplayer, I actively avoided adding buttons and album art and whatnot because I don't need them. So I don't know if I actually want to take the time to extend the extension much further than this, to make it work with other stuff. There's even a bug that I have yet to fix, which happens to involve specifically _not_ working with other mpris players.

By the way, I'd have simply (forked, updated and) used mheine's gnome-shell-spotify-label that you linked above, had I actually seen it before I'd already made my own. extensions.gnome hid it from me because it didn't support my gnome version, and I never really bothered to look deeper so I just never saw it.

As for the label format, I remember customizing the UI like that back in winamp days. That's just how it's done quite often. I simply defaulted to that format after my own idea turned out terrible.

So anyway, I'll take a deeper look at it when I have more time, but I'm not making any promises.
